name: Docker Build & Push

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t karoianroman/app:latest .

      - name: Stop previous container
        run: |
          docker stop app || true
          docker rm app || true

      - name: Run new container
        run: docker run -d -p 3000:3000 --name app app:latest
